[package]
name = "bin-layout"
version = "2.0.0"
edition = "2021"

description = "This library used to serialize and deserialize data in binary format."
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/bin-layout.rs"
license = "Apache-2.0"
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

[features]
no-overflow-checks = []
nightly = []
BE = []
NE = []

[dependencies]
derive = { path = "./derive", version = "0.2" }