[package]
name = "bin-layout"
version = "1.0.0"
edition = "2021"

description = "This library used to serialize and deserialize data in binary format."
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/bin-layout.rs"
license = "Apache-2.0"
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

[features]
nightly = []
BE = ["data-view/BE"]
NE = ["data-view/NE"]

[dependencies]
data-view = "5"
derive = { path = "./derive", version = "0.1" }