[package]
name = "bin-layout"
version = "4.0.0"
edition = "2021"

description = "This library used to serialize and deserialize data in binary format."
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/bin-layout.rs"
license = "Apache-2.0"
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

[features]

# Enable nightly features to enable optimization and performance.
nightly = []
auto_traits = ["nightly"]

# Endianness
BE = []         # Big Endian
NE = []         # Native Endian

# Variable-Length integer encoding types
L3 = []         # 22 bits

[dependencies]
bin-layout-derive = { path = "./bin_layout_derive", version = "0.2" }

[workspace]
members = ["bin_layout_derive"]